book/urls.py
from django.urls import path

# urls off function off views
# from .views import book, add_book, edit_book, delete_book, book_details

app_name = 'book'

'''
# urls off function based view
urlpatterns = [
    path('', book, name='book'),
    path('add/', add_book, name='add_book'),
    path('edit/<int:pk>/', edit_book, name='edit_book'),
    path('delete/<int:pk>/', delete_book, name='delete_book'),
    path('<int:pk>/', book_details, name='book_details'),
]
'''

# urls off class based view
from .views import BookListView, BookCreateView, BookUpdateView, BookDeleteView, BookDetailView ,book_list, book_detail , BookList, BookDetail, BookCreateAPIView, BookListAPIViews, BookUpdateAPIView, BookDeleteAPIView, BookRetrieveAPIView, BookRetrieveUpdateDestroyAPIView


urlpatterns = [
    path('', BookListView.as_view(), name='book'),
    path('add/', BookCreateView.as_view(), name='add_book'),
    path('edit/<int:pk>/', BookUpdateView.as_view(), name='edit_book'),
    path('delete/<int:pk>/', BookDeleteView.as_view(), name='delete_book'),
    path('details/<int:pk>/', BookDetailView.as_view(), name='book_details'),
    
    # api vith functions view
    path('api/list/', book_list, name='book_list'),
    path('api/detail/<int:pk>/', book_detail, name='book_detail'),
    
    # api with class based view
    path('api/book/', BookList.as_view(), name='book_list_views'),
    path('api/book/<int:pk>/', BookDetail.as_view(), name='book_detail_views'),
    
    # api with generic class based view
    path('api/book/generic', BookCreateAPIView.as_view(), name='book_create_generic'),
    path('api/book/generic/list', BookListAPIViews.as_view(), name='book_list_generic'),
    path('api/book/generic/update/<pk>/', BookUpdateAPIView.as_view(), name='book_update_generic'),
    path('api/book/generic/delete/<pk>/', BookDeleteAPIView.as_view(), name='book_delete_generic'),
    path('api/book/generic/retrieve/<pk>/', BookRetrieveAPIView.as_view(), name='book_dretieve_generic'),
    
    # api with generic class based view with CRUD operations in one place (retrieve, update, delete, create)  (CRUD - Create, Retrieve, Update, Delete)
    path('api/book/generic/rud/<id>/', BookRetrieveUpdateDestroyAPIView.as_view(), name='book_URD_generic'),
]

project/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from rest_framework_simplejwt.views import TokenObtainPairView, TokenRefreshView


urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/token/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('api/token/refresh/', TokenRefreshView.as_view(), name='token_refresh'), 
    path('user/',include('userauths.urls')),
    path('', include('book.urls', namespace='book')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

book/models.py
from django.db import models

# Create your models here.

status_books = [
    ('available', 'available'),
    ('rented', 'rented'),
    ('sold', 'sold'),
]

class Book(models.Model):
    title = models.CharField(max_length=200)
    author = models.CharField(max_length=200, blank=True)
    photo_book = models.ImageField(upload_to='photos_books', null=True, blank=True, default='book.jpg')
    photo_author = models.ImageField(upload_to='photos_authors', null=True, blank=True)
    pages = models.IntegerField()
    price = models.DecimalField(max_digits=5, decimal_places=2,null=True, blank=True)
    descripition = models.TextField(null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    active = models.BooleanField(default=True)
    status = models.CharField(max_length=50, choices=status_books, null=True, blank=True)

    def __str__(self):
        return self.title

book/forms.py
from django import forms
from .models import Book

class BookForm(forms.ModelForm):
    class Meta:
        model = Book
        fields = '__all__'

book/views.py
'''
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.decorators import login_required
from django.contrib import messages

from .models import Book
from .forms import BookForm

@login_required
def book(request):
    query = request.GET.get('search', '')
    books = Book.objects.filter(
        title__icontains=query
    ) | Book.objects.filter(
        author__icontains=query
    )
    context = {
        'books': books,
        'query': query
    }
    return render(request, 'book/home.html', context)

@login_required
def add_book(request):
    if request.method == 'POST':
        form = BookForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            messages.success(request, 'Book added successfully!')
            return redirect('book:book')
    else:
        form = BookForm()
    return render(request, 'book/add_book.html', {'form': form})

@login_required
def edit_book(request, pk):
    book = get_object_or_404(Book, pk=pk)
    if request.method == 'POST':
        form = BookForm(request.POST, request.FILES, instance=book)
        if form.is_valid():
            form.save()
            messages.success(request, 'Book updated successfully!')
            return redirect('book:book')
    else:
        form = BookForm(instance=book)
    return render(request, 'book/edit_book.html', {'form': form})

@login_required
def delete_book(request, pk):
    book = get_object_or_404(Book, pk=pk)
    if request.method == 'POST':
        book.delete()
        messages.success(request, 'Book deleted successfully!')
        return redirect('book:book')
    return render(request, 'book/delete_book.html', {'book': book})

@login_required
def book_details(request, pk):
    book = get_object_or_404(Book, pk=pk)
    context = {
        'book': book
    }
    return render(request, 'book/book_detail.html', context)
    
'''

from django.urls import reverse_lazy
from django.views.generic import ListView, CreateView, UpdateView, DeleteView, DetailView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib import messages
from django.db.models import Q 

from .models import Book
from .forms import BookForm


class BookListView(LoginRequiredMixin, ListView):
    model = Book
    template_name = 'book/home.html'
    context_object_name = 'books'
    
    def get_queryset(self):
        query = self.request.GET.get('search', '')
        return Book.objects.filter(
            Q(title__icontains=query) | Q(author__icontains=query)
        ).distinct()
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['query'] = self.request.GET.get('search', '')
        return context

class BookCreateView(LoginRequiredMixin, CreateView):
    model = Book
    form_class = BookForm
    template_name = 'book/add_book.html'
    
    def form_valid(self, form):
        messages.success(self.request, 'Book added successfully!')
        return super().form_valid(form)
    
    def get_success_url(self):
        return reverse_lazy('book:book')

class BookUpdateView(LoginRequiredMixin, UpdateView):
    model = Book
    form_class = BookForm
    template_name = 'book/edit_book.html'
    
    def form_valid(self, form):
        messages.success(self.request, 'Book updated successfully!')
        return super().form_valid(form)
    
    def get_success_url(self):
        return reverse_lazy('book:book')

class BookDeleteView(LoginRequiredMixin, DeleteView):
    model = Book
    template_name = 'book/delete_book.html'
    
    def delete(self, request, *args, **kwargs):
        messages.success(self.request, 'Book deleted successfully!')
        return super().delete(request, *args, **kwargs)
    
    def get_success_url(self):
        return reverse_lazy('book:book')

class BookDetailView(LoginRequiredMixin, DetailView):
    model = Book
    template_name = 'book/book_detail.html'
    context_object_name = 'book'



# API Views with functions
from rest_framework.decorators import api_view
from rest_framework.response import Response
from rest_framework import status

from .serializers import BookSerializer


@api_view(['GET', 'POST'])
def book_list(request):
    if request.method == 'GET':
        book = Book.objects.all()
        serializer = BookSerializer(book, many=True)
        return Response(serializer.data, status=200)
    elif request.method == 'POST':
        serializer = BookSerializer(data=request.data)
        if serializer.is_valid():
            serializer.save()
            return Response(serializer.data, status=status.HTTP_201_CREATED)
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)


@api_view(['GET', 'PUT', 'DELETE'])
def book_detail(request, pk):
    """
    Retrieve, update or delete a code book.
    """
    try:
        book = Book.objects.get(pk=pk)
    except Book.DoesNotExist: # ModelName.DoesNotExist not object_name.DoesNotExist
        return Response(status=status.HTTP_404_NOT_FOUND)

    if request.method == 'GET':
        serializer = BookSerializer(book)
        return Response(serializer.data)

    elif request.method == 'PUT': # scrol all data
        serializer = BookSerializer(book, data=request.data)
        if serializer.is_valid():
            serializer.save()
            return Response(serializer.data)
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)
    
    elif request.method == 'PATCH': # scrol chosiess data
        serializer = BookSerializer(book, data=request.data)
        if serializer.is_valid():
            serializer.save()
            return Response(serializer.data)
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)

    elif request.method == 'DELETE':
        book.delete()
        return Response(status=status.HTTP_204_NO_CONTENT)



# API with class based views
from rest_framework.views import APIView
from rest_framework.response import Response
from rest_framework import status
from django.http import Http404
from django_filters.rest_framework import DjangoFilterBackend
from rest_framework import filters



from .serializers import BookSerializer


class BookList(APIView):
    """
    List all book, or create a new book.
    """
    def get(self, request):
        book = Book.objects.all()
        serializer = BookSerializer(book, many=True)
        return Response(serializer.data)


    def post(self, request):
        book = BookSerializer(data=request.data)
        if book.is_valid():
            book.save()
            return Response(book.data, status=status.HTTP_201_CREATED)
        return Response(book.errors, status=status.HTTP_400_BAD_REQUEST)

    
class BookDetail(APIView):
    """
    Retrieve, update or delete a book instance.
    """
    def get_object(self, pk):
        try:
            return Book.objects.get(pk=pk)
        except Book.DoesNotExist:
            raise Http404
    
    def get(self, request, pk):
        book = self.get_object(pk)
        serializer = BookSerializer(book)
        return Response(serializer.data)


    def put(self, request, pk):
        book = self.get_object(pk)
        serializer = BookSerializer(book, data=request.data)
        if serializer.is_valid():
            serializer.save()
            return Response(serializer.data)
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)

    def patch(self, request, pk):
        book = self.get_object(pk)
        serializer = BookSerializer(book, data=request.data, partial=True)
        if serializer.is_valid():
            serializer.save()
            return Response(serializer.data)
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)
        
    def delete(self, request, pk):
        book = self.get_object(pk)
        book.delete()
        return Response(status=status.HTTP_204_NO_CONTENT)


 
# API with generic class based views
from rest_framework.generics import CreateAPIView, ListAPIView, UpdateAPIView, DestroyAPIView, RetrieveAPIView, RetrieveUpdateDestroyAPIView


class BookListAPIViews(ListAPIView):
    '''
    def get(self, request):
        book = Book.objects.all()
        serializer = BookSerializer(book, many=True)
        return Response(serializer.data)
    '''

    queryset = Book.objects.all()
    serializer_class = BookSerializer
    filter_backends = [DjangoFilterBackend,filters.SearchFilter,filters.OrderingFilter]
    filterset_fields = ['title']
    search_fields = ['title', 'author', 'descripition']
    ordering_fields = ['title', 'author']


    
    

class BookCreateAPIView(CreateAPIView):
    '''
    def post(self, request):
        book = BookSerializer(data=request.data)
        if book.is_valid():
            book.save()
            return Response(book.data, status=status.HTTP_201_CREATED)
        return Response(book.errors, status=status.HTTP_400_BAD_REQUEST)
    '''
    
    serializer_class = BookSerializer
    

class BookUpdateAPIView(UpdateAPIView):
    '''
    
    def put(self, request, pk):
        book = self.get_object(pk)
        serializer = BookSerializer(book, data=request.data)
        if serializer.is_valid():
            serializer.save()
            return Response(serializer.data)
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)

    def patch(self, request, pk):
        book = self.get_object(pk)
        serializer = BookSerializer(book, data=request.data, partial=True)
        if serializer.is_valid():
            serializer.save()
            return Response(serializer.data)
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)
    '''
    
    queryset = Book.objects.all()
    serializer_class = BookSerializer
    # lookup_field = "id"  # run search for id
    

class BookDeleteAPIView(DestroyAPIView):
    '''
    def delete(self, request, pk):
        book = self.get_object(pk)

book/templates/book/add_book.html
{% extends 'base.html' %}
{% load static %}
{% block body %}
<div class="container mt-4">
    <h1 class="mb-4">Add New Book</h1>
    
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        
        <div class="mb-3">
            {{ form.non_field_errors }}
        </div>
        
        {% for field in form %}
            <div class="mb-3">
                <label for="{{ field.id_for_label }}" class="form-label">{{ field.label }}</label>
                {{ field }}
                {{ field.errors }}
            </div>
        {% endfor %}
        
        <button type="submit" class="btn btn-primary">Add New Book</button>
    </form>

    <a href="{% url 'book:book' %}" class="btn btn-secondary mt-3">Back to Home</a>
</div>
{% endblock body %}

book/templates/book/book_detail.html
{% extends 'base.html' %}
{% block body %}

<div class="container mt-4">
    <h1 class="mb-4 animate__animated animate__fadeIn">Book Details</h1>

    <div class="card shadow-sm animate__animated animate__fadeIn animate__delay-1s">
        <div class="card-body">
            <div class="row mb-3">
                <div class="col-md-4">
                    <strong>Book Title:</strong>
                </div>
                <div class="col-md-8">
                    {{ book.title }}
                </div>
            </div>
            <div class="row mb-3">
                <div class="col-md-4">
                    <strong>Author:</strong>
                </div>
                <div class="col-md-8">
                    {{ book.author }}
                </div>
            </div>
            <div class="row mb-3">
                <div class="col-md-4">
                    <strong>Pages:</strong>
                </div>
                <div class="col-md-8">
                    {{ book.pages }}
                </div>
            </div>
            <div class="row mb-3">
                <div class="col-md-4">
                    <strong>Price:</strong>
                </div>
                <div class="col-md-8">
                    {{ book.price }}
                </div>
            </div>
            <div class="row mb-3">
                <div class="col-md-4">
                    <strong>Status:</strong>
                </div>
                <div class="col-md-8">
                    {{ book.get_status_display }}
                </div>
            </div>
            <div class="row mb-3">
                <div class="col-md-4">
                    <strong>Description:</strong>
                </div>
                <div class="col-md-8">
                    {{ book.descripition }}
                </div>
            </div>

            {% if book.photo_book %}
            <div class="row mb-3">
                <div class="col-md-4">
                    <strong>Book Image:</strong>
                </div>
                <div class="col-md-8">
                    <img src="{{ book.photo_book.url }}" alt="Book Image" class="img-fluid rounded border animate__animated animate__zoomIn" style="max-width: 300px;">
                </div>
            </div>
            {% endif %}

            {% if book.photo_author %}
            <div class="row mb-3">
                <div class="col-md-4">
                    <strong>Author Image:</strong>
                </div>
                <div class="col-md-8">
                    <img src="{{ book.photo_author.url }}" alt="Author Image" class="img-fluid rounded border animate__animated animate__zoomIn" style="max-width: 300px;">
                </div>
            </div>
            {% endif %}
        </div>
        <div class="card-footer text-end bg-light">
            <a href="{% url 'book:edit_book' book.pk %}" class="btn btn-primary">Edit Book</a>
            <a href="{% url 'book:delete_book' book.pk %}" class="btn btn-danger">Delete</a>
            <a href="{% url 'book:book' %}" class="btn btn-secondary">Back to Home</a>
        </div>
    </div>
</div>

{% endblock body %}

book/templates/book/delete_book.html
<!DOCTYPE html>
<html>
<head>
    <title>Delete Book</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            background-color: #f4f4f9;
            margin: 0;
            padding: 0;
            display: flex;
            justify-content: center;
            align-items: center;
            height: 100vh;
        }
        .container {
            background: #fff;
            border-radius: 8px;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
            padding: 20px;
            text-align: center;
            max-width: 400px;
            width: 100%;
        }
        h1 {
            color: #333;
        }
        p {
            color: #666;
        }
        button {
            background-color: #e74c3c;
            border: none;
            color: white;
            padding: 10px 20px;
            text-align: center;
            text-decoration: none;
            display: inline-block;
            font-size: 16px;
            margin: 10px 2px;
            cursor: pointer;
            border-radius: 5px;
        }
        button:hover {
            background-color: #c0392b;
        }
        a {
            color: #3498db;
            text-decoration: none;
            font-size: 16px;
        }
        a:hover {
            text-decoration: underline;
        }
    </style>
</head>
<body>
    <div class="container">
        <h1>Delete Book</h1>
        <p>Are you sure you want to delete "{{ book.title }} {{ book.title }}"?</p>
        <form method="post">
            {% csrf_token %}
            <button type="submit">Confirm</button>
            <br>
            <a href="{% url 'book:book' %}">Cancel</a>
        </form>
    </div>
</body>
</html>

book/templates/book/edit_book.html
{% extends 'base.html' %}
{% load static %}
{% block body %}
<div class="container mt-4">
    <h1 class="mb-4">Edit Book</h1>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="mb-3">
            {{ form.non_field_errors }}
            {{ form.as_p }}
        </div>
        <button type="submit" class="btn btn-primary">Save Book</button>
    </form>
    <a href="{% url 'book:book' %}" class="btn btn-secondary mt-3">Back to Home</a>
</div>
{% endblock body %}

book/templates/book/home.html
{% extends 'base.html' %}
{% load static %}

{% block body %}
<head>
    <style>
        .container {
            margin-top: 20px;
        }
        
        .grid-container {
            display: grid;
            grid-template-columns: repeat(4, 1fr);
            gap: 20px;
        }
        
        .card {
            border: 1px solid #dee2e6;
            border-radius: 0.375rem;
            overflow: hidden;
            display: flex;
            flex-direction: column;
            height: 100%;
            transition: transform 0.4s ease, box-shadow 0.4s ease, opacity 0.4s ease;
            opacity: 0;
            animation: fadeInUp 1s forwards;
            perspective: 1000px; /* Add perspective for 3D effects */
        }
        
        .card img {
            width: 100%;
            height: auto;
            border-bottom: 1px solid #dee2e6;
            transition: transform 0.4s ease, filter 0.4s ease;
        }
        
        .card img:hover {
            transform: scale(1.15);
            filter: brightness(1.2);
        }
        
        .card-body {
            padding: 20px;
            flex-grow: 1;
        }
        
        .card:hover {
            transform: translateY(-10px) rotateX(2deg) rotateY(2deg);
            box-shadow: 0 12px 24px rgba(0, 0, 0, 0.3);
        }
        
        .card-link {
            text-decoration: none;
            color: inherit;
        }
        
        .btn-primary {
            background-color: #007bff;
            border-color: #007bff;
            transition: background-color 0.3s ease, transform 0.3s ease;
        }
        
        .btn-primary:hover {
            background-color: #0056b3;
            border-color: #004085;
            transform: scale(1.05);
        }
        
        .btn-danger {
            background-color: #dc3545;
            border-color: #dc3545;
            transition: background-color 0.3s ease, transform 0.3s ease;
        }
        
        .btn-danger:hover {
            background-color: #c82333;
            border-color: #bd2130;
            transform: scale(1.05);
        }
        
        @keyframes fadeInUp {
            from {
                opacity: 0;
                transform: translateY(20px);
            }
            to {
                opacity: 1;
                transform: translateY(0);
            }
        }
        
        /* Additional animation for card links and hover effects */
        .card a {
            text-decoration: none;
            color: inherit;
            transition: color 0.3s ease;
        }
        
        .card a:hover {
            color: #007bff;
        }
    </style>
</head>



    <!-- Product Section -->
    <div class="container">
        <div class="grid-container">            
            {% for book in books %}

                <div class="card">

                    <a href="{% url 'book:book_details' book.pk %}">
                        {% if book.photo_book %}
                            <img src="{{ book.photo_book.url }}" style="width:306.9px; height:200px;" class="card-img-top" alt="Sample Image">
                        {% else %}
                            <img src="{% static 'assets/img/book.jpg' %}" style="width:218px; height:200px;" class="card-img-top" alt="Default Image">
                        {% endif %}
                    </a>
            
                    
                    <div class="card-body">
                        <a href="{% url 'book:book_details' book.pk %}" style="text-decoration: none;"><h5 class="card-title">{{book.title}}</h5></a>
                        <a href="{% url 'book:edit_book' book.pk %}" class="btn btn-primary">Edit Book</a>
                        <a href="{% url 'book:delete_book' book.pk %}" class="btn btn-danger">Delete</a>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>
{% endblock body %}